language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
script:
  - npm run build-storybook # 在推送到仓库时，直接发布到github page上
deploy:
  provider: pages # github page
  skip_cleanup: true
  github_token: $github_token  # github.com => settings => tokens
  local_dir: storybook-static # 部署的文件夹
  on:
    branch: master # GitHub page 所要查找的分支为master
  
  provider: npm
  skip_cleanup: true
  email: "120275191@qq.com"
  api_key: "YOUR_AUTH_TOKEN" # npm token
  local_dir: dist # 部署的文件夹
  on:
    branch: master # GitHub page 所要查找的分支为master